// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/google/wire"
	"practice/config"
	"practice/log"
)

// Injectors from wire.go:

func InitApp(cp config.ConfigPath, name string) (*Application, error) {
	viper, err := config.NewConfig(cp)
	if err != nil {
		return nil, err
	}
	options, err := log.NewLoggerOptions(viper)
	if err != nil {
		return nil, err
	}
	zapLoggers, err := log.NewZapLoggers(options)
	if err != nil {
		return nil, err
	}
	loggers, err := log.NewLoggers(zapLoggers)
	if err != nil {
		return nil, err
	}
	application, err := New(name, loggers)
	if err != nil {
		return nil, err
	}
	return application, nil
}

// wire.go:

var AppProvideSet = wire.NewSet(log.ProvideSet, ProvideSet, config.ProvideSet)
